import type { MarketingPageSpec } from '@/types/contracts'

export const platformPolicyEngineSpec: MarketingPageSpec = {
  id: 'platform-policy-engine',
  route: '/platform/policy-engine',
  title: 'Policy Engine // Inference Governance',
  description: 'Stateful behavioral inference with four operational regimes, thought composition for audit transparency, and anti-churn mode stability governance.',
  blocks: [
    {
      id: 'hero',
      type: 'hero',
      variant: 'compact',
      eyebrow: 'Platform // Inference Governance',
      headline: 'Every Decision Auditable. Every Transition Governed.',
      subheadline: 'The Policy Engine is the stateful inference core of the TubCorp platform. It evaluates normalized feature vectors at 10 Hz, manages operational regime transitions, and outputs governed decisions with full reasoning traces for compliance audit.',
      actions: [
        { id: 'harness', label: 'See Signal Processing', kind: 'route', target: '/platform/harness' },
        { id: 'observability', label: 'Observability Layer', kind: 'route', target: '/platform/observability' },
      ],
    },
    {
      id: 'regimes',
      type: 'featureGrid',
      eyebrow: 'Operational Regimes',
      title: 'Four States of Governed Response',
      columns: 4,
      items: [
        {
          title: 'Calm',
          body: 'Low-energy baseline. Conservative parameter governance with elevated pick diversity. The system observes and waits for meaningful signal before committing processing resources.',
        },
        {
          title: 'Engaged',
          body: 'Active tracking state. Balanced parameter governance with responsive mode transitions. The system is attending to sustained participant activity and adjusting output accordingly.',
        },
        {
          title: 'Intense',
          body: 'High-energy saturation. Aggressive parameter response with locked preset continuity. The system commits to the current configuration to maintain coherence under peak load.',
        },
        {
          title: 'Recovering',
          body: 'Post-intensity cooldown. Elevated stability bias with cautious parameter decay. The system de-escalates gracefully, preventing abrupt transitions that could destabilize the governed environment.',
        },
      ],
    },
    {
      id: 'inference-split',
      type: 'split',
      eyebrow: 'Inference Architecture',
      title: 'Hybrid Policy with Deterministic Fallback',
      body: 'The Policy Engine operates a hybrid inference architecture. When a trained model checkpoint is available, neural inference outputs are blended with deterministic policy at a configurable ratio. When no model is present — or when inference confidence drops below threshold — the system falls back entirely to hand-authored deterministic rules.\n\nThis architecture ensures that the governed environment never stops operating, regardless of model availability. Graceful degradation is a design constraint, not an edge case.',
      imagePosition: 'left',
      actions: [
        { id: 'platform', label: 'Full Platform Architecture', kind: 'route', target: '/platform' },
      ],
    },
    {
      id: 'thought-composition',
      type: 'prose',
      eyebrow: 'Transparency',
      title: 'Thought Composition and Reasoning Traces',
      body: 'Every policy decision is accompanied by a human-readable reasoning trace generated by the thought composition subsystem. The engine describes what it perceives in the acoustic environment — bass dominance, brightness shifts, transient events, energy spikes — and reports regime transitions and parameter adjustments in natural language.\n\nThese reasoning traces are streamed to operator surfaces in real time and archived in session logs. They serve a dual purpose: operational transparency for field operators during live deployments, and compliance documentation for post-session audit review.\n\nThe thought stream is not a summary. It is a continuous, frame-level accounting of the engine\'s decision-making process.',
    },
    {
      id: 'stability',
      type: 'split',
      eyebrow: 'Mode Stability',
      title: 'Anti-Churn Governance',
      body: 'The pick manager subsystem prevents rapid switching between presets, sample banks, instruments, and spatial patterns. Cooldown periods, stability-weighted change probability, and seeded deterministic randomness ensure that mode transitions feel intentional rather than erratic.\n\nA separate scheduling layer generates long-form novelty nudges at configurable intervals, biased by the current operational regime and time since the last pick change. This creates coherent arcs of variation without the instability of unconstrained stochastic selection.',
      imagePosition: 'right',
    },
    {
      id: 'training',
      type: 'prose',
      eyebrow: 'Continuous Improvement',
      title: 'Phase 1 Training Pipeline',
      body: 'The Policy Engine captures structured training pairs from every live deployment. Each inference frame records the input feature vector, the deterministic policy output, and the served blended output as a labeled training example.\n\nThis dataset feeds the Phase 1 supervised learning pipeline, enabling continuous model refinement without interrupting live operations. Human operator labels — recorded during deployment via the companion app — provide additional signal for preference learning.',
    },
    {
      id: 'contract',
      type: 'prose',
      eyebrow: 'Protocol Integrity',
      title: 'Contract-Locked Deployment',
      body: 'The Policy Engine enforces a strict protocol contract between the inference layer and the signal processing layer. Every deployment is locked to a pinned contract fingerprint — a SHA-256 hash of the canonical parameter definitions, mode-specific bounds, and required pick types.\n\nFingerprint mismatch between any platform component is a deployment blocker. This ensures that no component can emit parameters outside its contracted range, and no mode can operate without its required configuration. The contract is the single source of truth for what the platform can and cannot do.',
    },
    {
      id: 'cta',
      type: 'cta',
      variant: 'light',
      headline: 'Inference is only as good as the signals it governs.',
      body: 'See how the Harness provides continuous behavioral fingerprinting.',
      actions: [
        { id: 'harness', label: 'Signal Processing', kind: 'route', target: '/platform/harness' },
        { id: 'observability', label: 'Observability', kind: 'route', target: '/platform/observability' },
      ],
    },
  ],
}
